"""Workspace scaffolding — creates the directory structure for a new memory workspace."""

from __future__ import annotations

import subprocess
import sys
from datetime import date
from pathlib import Path

from .config import TYPE_FILES, TYPE_LABELS


def init_workspace(
    directory: Path,
    project_name: str = "AI Memory Protocol",
    author: str = "bburda",
    install_deps: bool = False,
) -> None:
    """Create a new memory workspace with all necessary files.

    Creates:
      - ``conf.py`` — Sphinx-Needs configuration
      - ``index.rst`` — root document
      - ``memory/index.rst`` — memory index with needtable
      - ``memory/*.rst`` — one file per memory type
      - ``Makefile`` — build shortcuts
      - ``.gitignore`` — ignore build artifacts
    """
    directory = directory.resolve()
    directory.mkdir(parents=True, exist_ok=True)

    year = date.today().year
    created: list[str] = []

    # conf.py
    _write(directory / "conf.py", _CONF_PY.format(
        project_name=project_name,
        author=author,
        year=year,
    ))
    created.append("conf.py")

    # index.rst
    _write(directory / "index.rst", _INDEX_RST.format(
        project_name=project_name,
        underline="=" * len(project_name),
    ))
    created.append("index.rst")

    # memory/index.rst
    (directory / "memory").mkdir(exist_ok=True)
    _write(directory / "memory" / "index.rst", _MEMORY_INDEX_RST)
    created.append("memory/index.rst")

    # memory/*.rst — one per type
    for mem_type, rel_path in TYPE_FILES.items():
        rst_path = directory / rel_path
        name = rel_path.split("/")[-1].replace(".rst", "")
        label = TYPE_LABELS.get(mem_type, name.title())
        header = name.title()
        _write(rst_path, _TYPE_RST.format(
            header=header,
            underline="=" * len(header),
            directive=mem_type,
            label=label,
        ))
        created.append(rel_path)

    # Makefile
    _write(directory / "Makefile", _MAKEFILE)
    created.append("Makefile")

    # .gitignore
    _write(directory / ".gitignore", _GITIGNORE)
    created.append(".gitignore")

    print(f"Initialized memory workspace at {directory}")
    print(f"  Created {len(created)} files:")
    for f in created:
        print(f"    {f}")

    if install_deps:
        print("\nInstalling dependencies...")
        venv_path = directory / ".venv"
        subprocess.run([sys.executable, "-m", "venv", str(venv_path)], check=True)
        pip = str(venv_path / "bin" / "pip")
        subprocess.run(
            [pip, "install", "-q", "sphinx", "sphinx-needs",
             "sphinxcontrib-plantuml", "sphinx-rtd-theme", "sphinx-design"],
            check=True,
        )
        print(f"  Dependencies installed in {venv_path}")

    print("\nNext steps:")
    print(f"  cd {directory}")
    if not install_deps:
        print("  python3 -m venv .venv && .venv/bin/pip install sphinx sphinx-needs sphinxcontrib-plantuml sphinx-rtd-theme sphinx-design")
    print("  memory add mem 'First observation' --tags 'topic:example'")
    print("  memory rebuild")
    print("  memory recall example")


def _write(path: Path, content: str) -> None:
    """Write content to a file, skipping if it already exists."""
    if path.exists():
        print(f"  Skipping {path.name} (already exists)")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


# ---------------------------------------------------------------------------
# Templates (embedded as strings to avoid pkg resource complexity)
# ---------------------------------------------------------------------------

_CONF_PY = '''\
# -- {project_name} — Sphinx Configuration --
# Generated by: ai-memory-protocol init

project = "{project_name}"
copyright = "{year}, {author}"
author = "{author}"
version = "0.1"
release = "0.1.0"

# -- Extensions -----------------------------------------------------------
extensions = [
    "sphinx_needs",
    "sphinx_design",
    "sphinxcontrib.plantuml",
]

# -- General ---------------------------------------------------------------
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", ".venv"]
templates_path = ["_templates"]
language = "en"

# -- HTML output -----------------------------------------------------------
html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
html_title = "{project_name}"

# ==========================================================================
# SPHINX-NEEDS CONFIGURATION
# ==========================================================================

# --------------------------------------------------------------------------
# 1. Need types
# --------------------------------------------------------------------------
needs_types = [
    {{"directive": "mem",  "title": "Observation",    "prefix": "MEM_",  "color": "#BDD7EE", "style": "node"}},
    {{"directive": "dec",  "title": "Decision",       "prefix": "DEC_",  "color": "#B6D7A8", "style": "node"}},
    {{"directive": "pref", "title": "Preference",     "prefix": "PREF_", "color": "#D5A6BD", "style": "node"}},
    {{"directive": "fact", "title": "Fact",            "prefix": "FACT_", "color": "#FFE599", "style": "node"}},
    {{"directive": "risk", "title": "Risk",            "prefix": "RISK_", "color": "#EA9999", "style": "node"}},
    {{"directive": "goal", "title": "Goal",            "prefix": "GOAL_", "color": "#A4C2F4", "style": "node"}},
    {{"directive": "q",    "title": "Open Question",   "prefix": "Q_",    "color": "#D9D2E9", "style": "node"}},
]

# --------------------------------------------------------------------------
# 2. Extra metadata fields
# --------------------------------------------------------------------------
needs_extra_options = {{
    "source":       {{"description": "Origin: URL, commit hash, ticket, conversation"}},
    "owner":        {{"description": "Who is responsible for this memory"}},
    "confidence":   {{"description": "Confidence level: low | medium | high"}},
    "scope":        {{"description": "Applicability scope: global, repo:X, product:X"}},
    "created_at":   {{"description": "ISO-8601 creation date"}},
    "updated_at":   {{"description": "ISO-8601 last update date"}},
    "expires_at":   {{"description": "ISO-8601 expiry date"}},
    "review_after": {{"description": "ISO-8601 date after which this memory needs review"}},
}}

# --------------------------------------------------------------------------
# 3. Custom link types
# --------------------------------------------------------------------------
needs_extra_links = [
    {{"option": "relates",     "incoming": "related by",       "copy": False, "style": "#888888", "style_part": "dotted"}},
    {{"option": "supports",    "incoming": "supported by",     "copy": False, "style": "#2E7D32"}},
    {{"option": "depends",     "incoming": "depended on by",   "copy": False, "style": "#1565C0"}},
    {{"option": "supersedes",  "incoming": "superseded by",    "copy": False, "style": "#E65100", "style_part": "bold"}},
    {{"option": "contradicts", "incoming": "contradicted by",  "copy": False, "style": "#C62828", "style_part": "bold"}},
    {{"option": "example_of",  "incoming": "has example",      "copy": False, "style": "#6A1B9A", "style_part": "dotted"}},
]

# --------------------------------------------------------------------------
# 4. Status workflow
# --------------------------------------------------------------------------
needs_statuses = [
    {{"name": "draft",      "description": "Freshly captured, not yet validated"}},
    {{"name": "active",     "description": "Validated and current"}},
    {{"name": "promoted",   "description": "Elevated to core knowledge"}},
    {{"name": "deprecated", "description": "Superseded or no longer valid"}},
    {{"name": "review",     "description": "Flagged for review"}},
]

# --------------------------------------------------------------------------
# 5. JSON export — the AI access layer
# --------------------------------------------------------------------------
needs_build_json = True
needs_id_regex = r"^[A-Za-z0-9_-]+"
needs_role_need_template = "[{{title}}]({{id}})"
'''

_INDEX_RST = '''\
{underline}
{project_name}
{underline}

Versioned, graph-based memory powered by `Sphinx-Needs <https://sphinx-needs.readthedocs.io/>`_.

.. toctree::
   :maxdepth: 2
   :caption: Memory

   memory/index
'''

_MEMORY_INDEX_RST = '''\
==============
Memory Index
==============

All memory entries organized by type.

.. toctree::
   :maxdepth: 1
   :glob:

   *

Summary
=======

.. needtable::
   :style: table
   :columns: id;type;title;status;tags;confidence
   :sort: status
'''

_TYPE_RST = '''\
{underline}
{header}
{underline}

Entries of type ``{directive}`` ({label}).

'''

_MAKEFILE = '''\
.PHONY: help html clean rebuild

SPHINXBUILD = sphinx-build
SPHINXOPTS  = -q
BUILDDIR    = _build

help: ## Show this help
\t@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \\
\t\tawk 'BEGIN {FS = ":.*?## "}; {printf "\\033[36m%-20s\\033[0m %s\\n", $$1, $$2}'

html: ## Build HTML + needs.json
\t$(SPHINXBUILD) -b html $(SPHINXOPTS) . $(BUILDDIR)/html

clean: ## Clean build artifacts
\trm -rf $(BUILDDIR)

rebuild: ## Rebuild needs.json
\tmemory rebuild
'''

_GITIGNORE = '''\
_build/
__pycache__/
*.pyc
*.egg-info/
.venv/
.DS_Store
Thumbs.db
'''
